### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by danirot** [ngneat/inspector#10]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I used ng add @ngneat/inspector. It was successful.
When i try to start the server i get the following error: 

ERROR in node_modules/@ngneat/inspector/lib/components/inspector-panel/inspector-tab/inspector-tab.component.d.ts:8:5 - error TS2416: Property 'emitter' in type 'In
spectorTabComponent' is not assignable to the same property in base type 'TabComponent'.
  Type 'EventEmitter<TabOutput>' is not assignable to type 'EventEmitter<CallFunctionOrOutput | Property>'.
    Types of property 'observers' are incompatible.
      Type 'Observer<TabOutput>[]' is not assignable to type 'Observer<CallFunctionOrOutput | Property>[]'.
        Type 'Observer<TabOutput>' is not assignable to type 'Observer<CallFunctionOrOutput | Property>'.
          Type 'CallFunctionOrOutput | Property' is not assignable to type 'TabOutput'.
            Type 'CallFunctionOrOutput' is not assignable to type 'TabOutput'.

      emitter: EventEmitter<TabOutput>;
      ~~~~~~~


## Expected behavior

<!-- Describe what the desired behavior would be. -->

## Minimal reproduction of the problem with instructions

## What is the motivation / use case for changing the behavior?

<!-- Describe the motivation or the concrete use case. -->

## Environment

<pre><code>
Angular version: 10.2.1
<!-- Check whether this is still an issue in the most recent Angular version -->

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.13.0  <!-- run `node --version` -->
- Platform:  Windows 

Others:
<!-- Anything else relevant?  Operating system version, IDE, package manager, HTTP server, ... -->
</code></pre>

**Comment by shhdharmen** [comment]
@danirot did you create project with `strict` mode?

**Comment by danirot** [comment]
@shhdharmen Yes.

**Comment by shhdharmen** [comment]
@danirot ok, I have pushed a beta version (1.0.1-beta.1) with a fix. Can you try installing again? Please follow below steps:

1. Delete node_modules and package-lock.json
2. Remove @ngneat/inspector from package.json
3. Run `npm i`
4. Run `ng add @ngneat/inspector@latest`
5. `ng serve`

Let me know if it works, I will release as full fix stable version.

**Comment by danirot** [comment]
@shhdharmen It works. The project started.
