### ISSUE TITLE
Add logging option

### ISSUE THREAD

**Issue by danirot** [ngneat/inspector#11]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I click on components and nothing happens or i get an error : Error while generating component!. 
It works on simple components. If i have an angular material component inside a custom component it does not work.

## Expected behavior
I will be nice if there is an option to enable logs that show in the console which element/component i clicked and if theres on errror then show the error trace.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shhdharmen** [comment]
@danirot can you provide the example on stackblitz? or you have a repo?

**Comment by danirot** [comment]
I have added a repo.

https://github.com/danirot/test-inspector

**Comment by BharathRavi27** [comment]
I am facing a similar issue even when inspecting simple components. Like @danirot said, an error trace would be helpful.

**Comment by shhdharmen** [comment]
@danirot I have pushed a beta version: `1.1.0-beta.1`, try to install using `ng add @ngneat/inspector@latest` and let me know if it works.

If any errors found, it should print on browser's console.

**Comment by shhdharmen** [comment]
This should also fix #14 and #13

**Comment by BharathRavi27** [comment]
It seems to be workung okay after update to `1.1.0-beta.1` in my case
