### ISSUE TITLE
Errors are not cleared in inspector.component.ts

### ISSUE THREAD

**Issue by codebreach** [ngneat/inspector#13]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
If the inspector errors for any component, it will show an error for all components after that.

## Expected behavior
The inspector should not show an error for components that it is able to detect.

Tested this by stepping through the code 
`getNgComponent` successfully returns but the inspector window still shows an error.

The fix is to reset `isErrored` in inspector.component.ts

```ts
try {
  this.activeComponent = getNgComponent(this.activeElement, this.hideNonSupportedProps, this.filterProps);
} catch (e) {
  this.isErrored = true;
}
```

needs to become

```ts
try {
  this.activeComponent = getNgComponent(this.activeElement, this.hideNonSupportedProps, this.filterProps);
  this.isErrored = false;
} catch (e) {
  this.isErrored = true;
}
```

**Comment by shhdharmen** [comment]
#11

**Comment by shhdharmen** [comment]
@codebreach I have pushed a beta version: `1.1.0-beta.1`, try to install using `ng add @ngneat/inspector@latest` and let me know if it works.

**Comment by codebreach** [comment]
Hard to verify now as the fix for #14 means that the errors no longer come as often. 

trying to make it fail to better verify but if you can share the PR i can verify that the error would be fixed or not

**Comment by shhdharmen** [comment]
This is the PR: #15

**Comment by codebreach** [comment]
Cool that should fix it
