### ISSUE TITLE
Fail to load component which has a property set to undefined

### ISSUE THREAD

**Issue by codebreach** [ngneat/inspector#14]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
For a component with a property that is set to undefined, we get an error on the line:
```ts
        (hideNonSupportedProps ? supportedTypes.includes(ngRawComponent[v].constructor.name) : true)
```
While the inspector handles the error, this causes any component with a property set to undefined to fail.

## Expected behavior
Inspector should still work.

Screenshots of the stacktraces and relevant locals:

![image](https://user-images.githubusercontent.com/501516/98240178-0afbf180-1f8f-11eb-8816-6ad90cb0cb04.png)
![image](https://user-images.githubusercontent.com/501516/98240201-118a6900-1f8f-11eb-9a08-ee8b8cd4ef6d.png)
![image](https://user-images.githubusercontent.com/501516/98240244-20711b80-1f8f-11eb-92ba-655690bee917.png)

Fix would involve changing:
```ts
        (hideNonSupportedProps ? supportedTypes.includes(ngRawComponent[v].constructor.name) : true)
```

to 
```ts
        (hideNonSupportedProps ? supportedTypes.includes(ngRawComponent[v]?.constructor.name) : true)
```

**Comment by shhdharmen** [comment]
@codebreach I have pushed a beta version: `1.1.0-beta.1`, try to install using `ng add @ngneat/inspector@latest` and let me know if it works.

**Comment by codebreach** [comment]
verified with `1.1.0-beta.1` :)
